theme: minima
title: FSL Blog
author: Tom O'Connell
email: fckstudentloanssite@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog dedicated to all things F*ckStudentLoans.

# social links
twitter_username: fckstudentloans

show_excerpts: true # set to false to remove excerpts on the homepage
